name: CI
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@master
        with:
          - node-version: 12.x
      - run: npm i -g yarn
      - run: yarn
      - run: yarn --scripts-prepend-node-path=auto run build
